services:
  - type: web
    name: react-portfolio
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Content-Type
        value: text/html
    routes:
      - type: rewrite
        source: /*
        destination: /index.html